name: .NET Build and Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        - cron: '0 * * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
              dotnet-version: '7.0.x'

        - name: Restore dependencies
          run: dotnet restore ./wwwroot # Update the path to your project or solution file

        - name: Build project
          run: dotnet build ./path/to/your/project_or_solution --no-restore --configuration Release # Update the path

        - name: Run tests
          run: dotnet test ./path/to/your/project_or_solution --no-build --verbosity normal # Update the path

        - name: Custom script - Check for TODO comments
          run: |
            echo "Verificando comentários TODO no código..."
            grep -r "TODO" . || echo "Nenhum TODO encontrado." || true