name: .NET Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        - cron: '0 * * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
              dotnet-version: '7.0.x'

        - name: Custom script - Check for TODO comments
          run: |
            echo "Verificando comentários TODO no código..."
            grep -r "TODO" . || echo "Nenhum TODO encontrado." || true